version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - navikt/copilot
    assignees:
      - navikt/copilot
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - navikt/copilot
    assignees:
      - navikt/copilot
    groups:
      github-actions:
        patterns:
          - "*"
