version: 1

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - navikt/jobbsporet
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - navikt/jobbsporet
    groups:
      github-actions:
        patterns:
          - "*"
