public class IPS_ParticipantPortalEvent {
   @AuraEnabled public String Emne{get;set;}
   @AuraEnabled public String Type{get;set;}
   @AuraEnabled public String Status{get;set;}
   @AuraEnabled public String TilDato{get;set;}
   @AuraEnabled public String FraDato{get;set;}
   @AuraEnabled public String ForfallsDato{get;set;}
   @AuraEnabled public String RelatertTil{get;set;}
   @AuraEnabled public String RelatertNavnKontakt{get;set;}
   @AuraEnabled public String Tildelt{get;set;}
}