name: "[HELPER] Deploy to Production"
on:
  workflow_dispatch:
    inputs:
      packageId:
        description: "Package ID"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy-to-production:
    name: Deploy to Production
    uses: navikt/crm-workflows-base/.github/workflows/deployPackage.yml@48483bf32c2b6f89c31e7d50e25b5fe6fac45ca2 # master
    permissions:
      contents: read
    with:
      packageId: ${{ inputs.packageId }}
      org: prod
      unpackagable: ./force-app/unpackagable-with-auto-deploy
    secrets: inherit