name: "[HELPER] Promote Package"
on:
  workflow_dispatch:
    inputs:
      packageId:
        description: "Package ID"
        required: true
      comment:
        description: "Release Comment"
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  debug:
    name: Debug Information
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Print input values
        run: |
          echo "Promoting Package ID: ${{ github.event.inputs.packageId }}"
          echo "Initiator: ${{ github.actor }}"

  run-package-promotion:
    name: Promote Package
    uses: navikt/crm-workflows-base/.github/workflows/packagePromotion.yml@b2a868d2ab462a8f6708a889e1f6ecb779e68199 # master
    permissions:
      contents: write
      pull-requests: write
    with:
      packageId: ${{ inputs.packageId }}
      comment: ${{ inputs.comment }}
    secrets: inherit