name: "[HELPER] Deploy to Production"
on:
  workflow_dispatch:
    inputs:
      packageId:
        description: "Package ID"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy-to-production:
    name: Deploy to Production
    uses: navikt/crm-workflows-base/.github/workflows/deployPackage.yml@b2a868d2ab462a8f6708a889e1f6ecb779e68199 # master
    permissions:
      contents: read
    with:
      packageId: ${{ inputs.packageId }}
      org: prod
      unpackagable: ./force-app/unpackagable-with-auto-deploy
    secrets: inherit