name: "[HELPER] Create Scratch Org"
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: "New branch (or pick existing above)"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  create-scratch-org:
    name: Create Scratch Org
    uses: navikt/crm-workflows-base/.github/workflows/createScratchOrg.yml@aad6b4f48e419d71490db436da697cd7581a2c6a
    with:
      branchName: ${{ github.event.inputs.branchName }}
    secrets: inherit