name: "[HELPER] Create Scratch Org"
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: "New branch (or pick existing above)"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  create-scratch-org:
    name: Create Scratch Org
    uses: navikt/crm-workflows-base/.github/workflows/createScratchOrg.yml@b2a868d2ab462a8f6708a889e1f6ecb779e68199 # master
    with:
      branchName: ${{ github.event.inputs.branchName }}
    secrets: inherit