name: "[PUSH] Create Package"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "force-app/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  create-package:
    name: Run Package Creation
    uses: navikt/crm-workflows-base/.github/workflows/packageCreate.yml@b2a868d2ab462a8f6708a889e1f6ecb779e68199 # master
    permissions:
      contents: write
    secrets: inherit